apiVersion: v2
name: application
description: A Helm chart for deploying applications with Deployments, CronJobs, and supporting resources
type: application
version: 0.0.7
appVersion: "1.0"
keywords:
  - application
  - deployment
  - cronjob
maintainers:
  - name: Gustavo Falco